name: Front-End Tests

# Run when pushing to a side branch or manually triggered/called
on:
  push:
    branches-ignore: ["crown"] # On crown it's run as part of the release pipeline
    paths:
      - ".github/workflows/frontend_tests.yml"
      - "src/**"
      - "package.json"
      - "yarn.lock"
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.event_name == 'workflow_call' && format('frontend-tests-{0}-{1}', github.workflow, github.run_id) || format('frontend-tests-{0}-{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

env:
  VITE_TRANSLATION_EMAIL: ${{ vars.VITE_TRANSLATION_EMAIL }}

jobs:
  test-react:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      ## Setup dependencies ##
      - name: Setup Node.js with Yarn caching
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install

      ## Tests ##
      - name: Run tests
        run: yarn test
