name: Release Pipeline

# Run when pushing to crown or manually triggered
on:
  push:
    branches: ["master", "crown"]
  workflow_dispatch:

# Only allow one job to run at a time per branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Allow this workflow to trigger actions on other branches
permissions:
  contents: write
  actions: write

env:
  DEPLOY_BRANCH: heroku
  GH_PAGES_BRANCH: gh-pages

jobs:
  # Run front-end tests
  run_frontend_tests:
    name: Run Front-End Tests
    uses: ./.github/workflows/frontend_tests.yml

  # Deploy to GitHub Pages
  deploy_to_gh_pages:
    name: Deploy to GitHub Pages
    needs: run_frontend_tests
    runs-on: ubuntu-latest
    env:
      VITE_TRANSLATION_EMAIL: ${{ vars.VITE_TRANSLATION_EMAIL }}
      VITE_DEPLOY_ENV: gh-pages
    steps:
    # Checkout the code
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    ## Setup dependencies ##
    - name: Setup Node.js with Yarn caching
      uses: actions/setup-node@v4
      with:
        node-version: "22.x"
        cache: yarn
        cache-dependency-path: yarn.lock

    # Install dependencies
    - name: Install dependencies
      run: yarn install

    # Build the app ##
    - name: Build app
      run: yarn build

    # Push to GitHub Pages ##
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        publish_branch: ${{ env.GH_PAGES_BRANCH }}
        destination_dir: crown
        keep_files: true
